default:
  image: golang:1.13

stages:
- test
- build
- deploy_pages

test:
  except: 
    - schedules
  stage: test
  script:
    - go test -v ./...
build:
  only: 
    - tags
  stage: build
  script:
    - curl -sL https://git.io/goreleaser | bash

deploy_pages:
  script:
    - chmod +x godownloader.sh
    - ./godownloader.sh -d
    - git clone --depth 1 https://gitlab.com/n8225/awesome-selfhosted.git --branch master --single-branch /tmp/awesome-selfhosted
    - rm /tmp/awesome-selfhosted/list/*
    - Awesome-Selfhosted-Gen --path /tmp/awesome-selfhosted/README.md --ghtoken $GITHUB_TOKEN
    - git clone --depth 1 --single-branch --branch gh-pages https://n8225:$GITHUB_TOKEN@github.com/n8225/awesome-selfhosted-gen.git public
    - mv index.html public/. && mv static public/.
    - git config user.email "n8225@gmail.com" && git config user.name "Nathan"
    - git add -A
    - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push
  artifacts:
    paths:
    - public
  only: 
    - schedules

