default:
  image: golang:1.15

stages:
- test
- build
- pages

test:
  except: 
    - schedules
  stage: test
  script:
    - go test -v ./...

build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    GORELEASER_IMAGE: goreleaser/goreleaser:latest

    DOCKER_REGISTRY: https://index.docker.io/v1/

    GIT_DEPTH: 0
    
  only:
    refs:
      - tags

  script: |
    docker pull $GORELEASER_IMAGE

    # GITLAB_TOKEN is needed to create GitLab releases.
    # DOCKER_* are needed to push Docker images.
    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/n8225/awesome-selfhosted-gen \
      -w /go/src/gitlab.com/n8225/awesome-selfhosted-gen \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e $GITHUB_TOKEN \
      $GORELEASER_IMAGE release --rm-dist

pages:
  script:
    - chmod +x godownloader.sh
    - ./godownloader.sh -d
    - git clone --depth 1 https://gitlab.com/n8225/awesome-selfhosted.git --branch master --single-branch /tmp/awesome-selfhosted
    - rm list/*
    - ./bin/awesome-selfhosted-gen --path /tmp/awesome-selfhosted/README.md --ghtoken $GITHUB_TOKEN
    - git clone --depth 1 --single-branch --branch gh-pages https://n8225:$GITHUB_TOKEN@github.com/n8225/awesome-selfhosted-gen.git public
    - cd public
    - rm -rf static
    - mv ../index.html . && mv ../static static
    - git config user.email "n8225@gmail.com" && git config user.name "Nathan"
    - git add -A
    - git commit -m "Build from $CI_SERVER_NAME $CI_PIPELINE_ID"
    - git push
  artifacts:
    paths:
    - public
  only: 
    - schedules
