name: Deploy
on: 
  schedule:
   - cron:  '0 7 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: build 
      run: go build .
    - name: Clone Awesome-Selfhosted 
      run: git clone --depth 1 https://github.com/awesome-selfhosted/awesome-selfhosted.git --branch master --single-branch /tmp/awesome-selfhosted
    - name: clean
      run: rm list/*
    - name: generate updated json
      run: ./awesome-selfhosted-gen --path /tmp/awesome-selfhosted/README.md --ghtoken ${{secrets.GITHUB_TOKEN}}
    - name: prep files
      run: mkdir public && mv index.html public/. && mv static public/.
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0 
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
