name: Deploy
on: push

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Get latest Release
      run: wget https://github.com/n8225/awesome-selfhosted-gen/releases/download/v0.1.1/awesome-selfhosted-gen_0.1.1_linux_amd64.tar.gz && tar xvzf awesome-selfhosted-gen_0.1.1_linux_amd64.tar.gz && pwd && ls
    - name: Clone Awesome-Selfhosted 
      run: git clone https://github.com/Kickball/awesome-selfhosted.git /tmp/awesome-selfhosted
    - name: generate updated json
      run: ./awesome-selfhosted-gen/awesome-selfhosted-gen --path /tmp/awesome-selfhosted/README.md --ghtoken ${{secrets.GITHUB_TOKEN}}
    - name: prep files
      run: mkdir public && mv index.html public/. && mv static public/.
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0 
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public